### ISSUE TITLE
[Suggestion] Mod config should allow default priority level

### ISSUE THREAD

**Issue by frenchiveruti** [FluffierThanThou/WorkTab#78] opened 2017-12-05 21:39 UTC
With the expansion on the amount of levels we can use, it would be nice that also we can have a "default" priority level for all the jobs when a new pawn joins.  
Like, right now we can set the amount of levels we want (9 by default) but not the default priority level (which defaults to 3).
If you include this in the mod, keep in mind you should make the default level dependant on the amount of levels (so the player can't set 8 by default when he selects only 5 levels of priority max).
Thanks fluffy.

**Comment by FluffierThanThou** [comment] 2017-12-06 09:08
duplicate of #31

**Closed by FluffierThanThou** 2017-12-06 09:08 UTC

**Comment by frenchiveruti** [comment] 2017-12-06 12:51
Lol my own suggestion haha sorry
