### ISSUE TITLE
Expanded Priority Tab Not Displaying Correctly.

### ISSUE THREAD

**Issue by camk16** [FluffierThanThou/WorkTab#75] opened 2017-10-22 02:03 UTC
![untitled](https://user-images.githubusercontent.com/30790283/31857385-dec98146-b69a-11e7-85b1-f79a99820c42.png)

**Comment by FluffierThanThou** [comment] 2017-11-10 20:52
duplicate of #67

**Closed by FluffierThanThou** 2017-11-10 20:52 UTC
