### ISSUE TITLE
Ultrawide Display Issue

### ISSUE THREAD

**Issue by deLaDude** [FluffierThanThou/WorkTab#104] opened 2018-11-01 18:46 UTC
I tried this mod on a new colony last night and had to disable it because the work column labels do not display properly which makes it unusable. Particularly in the detailed task view which is what I was looking forward to using. The labels are all shifted off of the tab up and to the right.

I am playing at 3440x1440 resolution / Windows 8 / 64-bit

Let me know if you need any additional information or want a screen shot.

**Comment by FluffierThanThou** [comment] 2018-11-01 20:45
duplicate of #77

**Closed by FluffierThanThou** 2018-11-01 20:45 UTC
