### ISSUE TITLE
Work Priorities resetting

### ISSUE THREAD

**Issue by Ayrlixx** [FluffierThanThou/WorkTab#37] opened 2017-01-15 21:21 UTC
Having the same issue as .Blue on the steam page with my work orders resetting to defaults, except for certain pawns.

Logs link; https://gist.github.com/HugsLibRecordKeeper/5ec4659b6984a29df7aadd9cdb80bba8

Screenshot of the work orders; https://gyazo.com/54f666e942ba3b129c858d47c27b5d16

If I had to guess, I would say that the blank one and the one with different numbers are the original characters I set the rules on (without the timers). I used to have a blank favourite saved, and a "Favourite-Timers" one saved, then just pasted to the others with changing individual rules.

Before all this happened, hospitality updated again and it caused the original issue I had where I couldn't reload the save, so I did your recommended fix which loaded the save up but gave me that screenshot of work orders, I then reset them to how I had, saved and quit, back on few hours later and it seemed to not keep them registered, including the favourites options I had.

Hope that's enough info for you, let me know if you want/need anything else, thanks!

**Comment by Cynsity702** [comment] 2017-01-17 20:29
http://textuploader.com/ddwc5

Same issue, loaded a saved game and then they crashed.

Also in that error log, the errors at the bottom are for a new game i just started after loading some new mods. I got an error when the wanderer joined incident happened. I don't know what the error is but it popped up so i figured id share. Might also be an issue with OUTFITTER. I think i ran with you on this before. Let me know what you come up with.

**Comment by Rezendore** [comment] 2017-01-22 22:16
Same issue here.
This is the mods I am using in order.

https://gyazo.com/50a738ac12656557adfb57aed152da40

Another weird thing is that my colonists are randomly holding doors open, leading to a lot of bad things like raiders and mad animals getting into my base. Not sure if this has anything to do with Allow Tool however.

**Comment by Ayrlixx** [comment] 2017-01-22 23:26
Noticed you have Psychology, that does have an "event" where random pawns will be "saboteurs" and do things like leaving doors open, might be that that is causing the doors on your save to be left open. Afaik you can turn that off in the options menu for the mods, if you don't actually have it on then possible it is forced on due to some mod conflict.

**Comment by FluffierThanThou** [comment] 2017-01-26 21:30
There's several different things going on in this thread.

@Ayrlixx; The initial report I've been unable to replicate, and there's no reason the caches should keep invalidating after the reset. You do have various warnings and errors in the log from other mods, which as far as I'm concerned pretty much invalidates the warranty. I just don't know what the interactions of all those mods do - especially if they throw errors on load.

@Cynsity702; by and large, the same response. You have too many mods, and they're throwing too many errors, for me to be able to do anything. The final error in the log is from my mod, but it's a duplicate of issue #40, not this one. 

@Rezendore; I can't do anything without an output log. You can normally find the output log in the following location; `C:\Program Files\Steam\steamapps\common\RimWorld\RimWorldWin_Data\output_log.txt`. If you changed the steam install location, alter the path accordingly. Since you have this mod, you should also have HugsLib, so you could just open the console '`', and press the share button there.

I'm now closing this issue. If you feel that is a mistake, please start a new issue, with a clear description of what happens, what you expected to happen, and *most importantly*, an output_log.

**Closed by FluffierThanThou** 2017-01-26 21:30 UTC
Labels: trying to replicate
